// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (name)
VALUES ($1)
RETURNING id, name, status, current_turn, created_at, updated_at
`

func (q *Queries) CreateGame(ctx context.Context, name string) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, name)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CurrentTurn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, name, status, current_turn, created_at, updated_at FROM games WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CurrentTurn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, name, status, current_turn, created_at, updated_at FROM games ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CurrentTurn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
