// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveInvitation = `-- name: ArchiveInvitation :exec
UPDATE invitations
SET archived_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (email, code, invited_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code, invited_by, used_by, used_at, expires_at, archived_at, created_at
`

type CreateInvitationParams struct {
	Email     string
	Code      string
	InvitedBy uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Code,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.InvitedBy,
		&i.UsedBy,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByCode = `-- name: GetInvitationByCode :one
SELECT id, email, code, invited_by, used_by, used_at, expires_at, archived_at, created_at FROM invitations WHERE code = $1
`

func (q *Queries) GetInvitationByCode(ctx context.Context, code string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCode, code)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.InvitedBy,
		&i.UsedBy,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, email, code, invited_by, used_by, used_at, expires_at, archived_at, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.InvitedBy,
		&i.UsedBy,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT i.id, i.email, i.code, i.invited_by, i.used_by, i.used_at, i.expires_at, i.archived_at, i.created_at,
       u.handle AS invited_by_handle
FROM invitations i
JOIN users u ON u.id = i.invited_by
WHERE i.archived_at IS NULL
  AND (
    $1::text = ''
    OR ($1::text = 'used' AND i.used_at IS NOT NULL)
    OR ($1::text = 'unused' AND i.used_at IS NULL AND i.expires_at > NOW())
    OR ($1::text = 'expired' AND i.used_at IS NULL AND i.expires_at <= NOW())
  )
ORDER BY i.created_at DESC
`

type ListInvitationsRow struct {
	ID              uuid.UUID
	Email           string
	Code            string
	InvitedBy       uuid.UUID
	UsedBy          pgtype.UUID
	UsedAt          pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	InvitedByHandle string
}

func (q *Queries) ListInvitations(ctx context.Context, filter string) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsRow
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Code,
			&i.InvitedBy,
			&i.UsedBy,
			&i.UsedAt,
			&i.ExpiresAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.InvitedByHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE invitations
SET used_by = $2, used_at = NOW()
WHERE id = $1
`

type MarkInvitationUsedParams struct {
	ID     uuid.UUID
	UsedBy pgtype.UUID
}

func (q *Queries) MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error {
	_, err := q.db.Exec(ctx, markInvitationUsed, arg.ID, arg.UsedBy)
	return err
}

const updateInvitationExpiry = `-- name: UpdateInvitationExpiry :exec
UPDATE invitations
SET expires_at = $2
WHERE id = $1
`

type UpdateInvitationExpiryParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateInvitationExpiry(ctx context.Context, arg UpdateInvitationExpiryParams) error {
	_, err := q.db.Exec(ctx, updateInvitationExpiry, arg.ID, arg.ExpiresAt)
	return err
}
