// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwt_signing_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJWTSigningKey = `-- name: CreateJWTSigningKey :one
INSERT INTO jwt_signing_keys (
    token_type,
    algorithm,
    secret,
    state,
    verify_until
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
`

type CreateJWTSigningKeyParams struct {
	TokenType   string
	Algorithm   string
	Secret      []byte
	State       string
	VerifyUntil pgtype.Timestamptz
}

func (q *Queries) CreateJWTSigningKey(ctx context.Context, arg CreateJWTSigningKeyParams) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, createJWTSigningKey,
		arg.TokenType,
		arg.Algorithm,
		arg.Secret,
		arg.State,
		arg.VerifyUntil,
	)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJWTSigningKey = `-- name: DeleteJWTSigningKey :exec
DELETE FROM jwt_signing_keys
WHERE id = $1
`

func (q *Queries) DeleteJWTSigningKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJWTSigningKey, id)
	return err
}

const getActiveJWTSigningKey = `-- name: GetActiveJWTSigningKey :one
SELECT id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
FROM jwt_signing_keys
WHERE token_type = $1
  AND state = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveJWTSigningKey(ctx context.Context, tokenType string) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveJWTSigningKey, tokenType)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveJWTSigningKeyForUpdate = `-- name: GetActiveJWTSigningKeyForUpdate :one
SELECT id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
FROM jwt_signing_keys
WHERE token_type = $1
  AND state = 'active'
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetActiveJWTSigningKeyForUpdate(ctx context.Context, tokenType string) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveJWTSigningKeyForUpdate, tokenType)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJWTSigningKeyByID = `-- name: GetJWTSigningKeyByID :one
SELECT id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
FROM jwt_signing_keys
WHERE id = $1
`

func (q *Queries) GetJWTSigningKeyByID(ctx context.Context, id uuid.UUID) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, getJWTSigningKeyByID, id)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJWTSigningKeyByIDForUpdate = `-- name: GetJWTSigningKeyByIDForUpdate :one
SELECT id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
FROM jwt_signing_keys
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetJWTSigningKeyByIDForUpdate(ctx context.Context, id uuid.UUID) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, getJWTSigningKeyByIDForUpdate, id)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retireJWTSigningKey = `-- name: RetireJWTSigningKey :one
UPDATE jwt_signing_keys
SET
    state = 'retired',
    verify_until = $2
WHERE id = $1
RETURNING id, token_type, algorithm, secret, state, verify_until, created_at, updated_at
`

type RetireJWTSigningKeyParams struct {
	ID          uuid.UUID
	VerifyUntil pgtype.Timestamptz
}

func (q *Queries) RetireJWTSigningKey(ctx context.Context, arg RetireJWTSigningKeyParams) (JwtSigningKey, error) {
	row := q.db.QueryRow(ctx, retireJWTSigningKey, arg.ID, arg.VerifyUntil)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.TokenType,
		&i.Algorithm,
		&i.Secret,
		&i.State,
		&i.VerifyUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
