// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Invitation struct {
	ID         uuid.UUID
	Email      string
	Code       string
	InvitedBy  uuid.UUID
	UsedBy     pgtype.UUID
	UsedAt     pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type JwtSigningKey struct {
	ID          uuid.UUID
	TokenType   string
	Algorithm   string
	Secret      []byte
	State       string
	VerifyUntil pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Role struct {
	ID          int64
	Name        string
	Description string
}

type User struct {
	ID           uuid.UUID
	Handle       string
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    int64
	CreatedAt pgtype.Timestamptz
}
