// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, r.id
FROM roles r
WHERE r.name = $2
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AddRoleToUserParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.Exec(ctx, addRoleToUser, arg.UserID, arg.Name)
	return err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
    handle = $2,
    email = $3,
    is_active = $4
WHERE id = $1
RETURNING id, handle, email, password_hash, is_active, created_at, updated_at
`

type AdminUpdateUserParams struct {
	ID       uuid.UUID
	Handle   string
	Email    string
	IsActive bool
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUser,
		arg.ID,
		arg.Handle,
		arg.Email,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*)
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE r.name = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    handle,
    email,
    password_hash,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, handle, email, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Handle       string
	Email        string
	PasswordHash string
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Handle,
		arg.Email,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, handle, email, password_hash, is_active, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, handle, email, password_hash, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAuthByEmail = `-- name: GetUserForAuthByEmail :one
SELECT id, handle, email, password_hash, is_active, created_at, updated_at
FROM users u
WHERE u.email = $1
`

func (q *Queries) GetUserForAuthByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForAuthByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoleNamesByUser = `-- name: ListRoleNamesByUser :many
SELECT r.name
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) ListRoleNamesByUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleNamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description
FROM roles
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRoles = `-- name: ListUsersWithRoles :many
SELECT u.id, u.handle, u.email, u.password_hash, u.is_active, u.created_at, u.updated_at,
       COALESCE(r.name, '') AS role_name
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
ORDER BY u.created_at DESC, u.id, r.name
`

type ListUsersWithRolesRow struct {
	ID           uuid.UUID
	Handle       string
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	RoleName     string
}

func (q *Queries) ListUsersWithRoles(ctx context.Context) ([]ListUsersWithRolesRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRolesRow
	for rows.Next() {
		var i ListUsersWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllRolesFromUser = `-- name: RemoveAllRolesFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) RemoveAllRolesFromUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllRolesFromUser, userID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    handle = $2,
    email = $3
WHERE id = $1
RETURNING id, handle, email, password_hash, is_active, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID     uuid.UUID
	Handle string
	Email  string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Handle, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
